#this is workflow
name : Hello workflow
#runs on triggers
on :
  push :
     branches : [main]

#this is job inside the  workflows
jobs :
#this is name of the job    
   greet:
   #this is the github runner ,each job runs on a runner
       runs-on : ubuntu-latest
       steps:
          - name : say hello to user
            run : echo "hello dosto"

          - name : say hello to user
            run : echo "hello $USER"
details :
   runs-on : ubuntu-latest
   steps:
   - name : show what is the version of python ,docker , etc
     run : docker --version && python --version

          
